### ISSUE TITLE
Getting error after selecting combos

### ISSUE THREAD

**Issue by jashgro** [BLUE-DEVIL1134/IronEye#10]
**Describe the bug**
https://del.dog/IronEyeLogs.txt

**To Reproduce**
1. Execute script
2. Select Zee5
3. Enter Combos name

Screenshot 
![IMG_20201024_162948_131](https://user-images.githubusercontent.com/61772939/97080042-27ef0700-1616-11eb-988d-5808b2175080.jpg)

**Comment by BLUE-DEVIL1134** [comment]
i Will Solve The Issue In 10-15 Minuetes.

**Comment by BLUE-DEVIL1134** [comment]
And Its Done...
