### ISSUE TITLE
Error in HMA Checker.

### ISSUE THREAD

**Issue by INSANELYOFFICIAL** [BLUE-DEVIL1134/IronEye#12]
1. Go to IronEye Folder using cd.
2. Start the IronEye using python -m IronEye.
3. Run HideMyAss Checker.
3. Add Combo file name.
4. Wait for it to check some combos

Combos used were Clean. Internet was working Fine. Wasn't using any other applications while the checker was running.

![Screenshot_20201105-150330.jpg](https://user-images.githubusercontent.com/24321440/98225151-62439700-1f7a-11eb-91a3-0708cd603ebd.jpg)

**Comment by BLUE-DEVIL1134** [comment]
i am fixing the error
the update 2.7 will solve it with new checkers

**Comment by INSANELYOFFICIAL** [comment]
> i am fixing the error
> the update 2.7 will solve it with new checkers

Please also add an feature where it skips the specific line in combo if it isn't in correct format instead of giving error. This feature would be extremely useful.

**Comment by BLUE-DEVIL1134** [comment]
> > i am fixing the error
> > the update 2.7 will solve it with new checkers
> 
> Please also add an feature where it skips the specific line in combo if it isn't in correct format instead of giving error. This feature would be extremely useful.

sure
but the update has not yet come
so i am reopening the issue

**Comment by BLUE-DEVIL1134** [comment]
nest update will remove all these
the update is tommorow
