### ISSUE TITLE
2 Different Errors In Altbalaji Checker.

### ISSUE THREAD

**Issue by INSANELYOFFICIAL** [BLUE-DEVIL1134/IronEye#13]
1. Go to IronEye Folder using cd.

2. Start the IronEye using python -m IronEye.

3. Run Altbalaji Checker.

4. Add Combo file name.

5. See error.

Internet was working Fine. Termux wasn't running on background.

(1) The checker gives bad hits.

![Screenshot_20201111-181221.jpg](https://user-images.githubusercontent.com/24321440/98813742-b2bf6680-244a-11eb-914a-4282d35e5433.jpg)

(2) After entering the combo file name it gives the error shown in below image.

(Combos are different from the previous image.)

![Screenshot_20201111-182210.jpg](https://user-images.githubusercontent.com/24321440/98813915-f2864e00-244a-11eb-969b-3aa25217fdf6.jpg)

**Comment by BLUE-DEVIL1134** [comment]
the first one is a bug
but the second one has some other problem

i will be solving that. soon

**Comment by BLUE-DEVIL1134** [comment]
nest update will remove all these
the update is tommorow
