### ISSUE TITLE
About custom config

### ISSUE THREAD

**Issue by jataian** [BLUE-DEVIL1134/IronEye#29]
Please tell me how can I use custom config in ironeye

**Comment by BLUE-DEVIL1134** [comment]
Oh, It's Not For Users Now, Its just for developers right now....

Next update on 14 April will add custom config option for all...

**Comment by BLUE-DEVIL1134** [comment]
Till then let this be open,
Will close with the pr for new update.

And sorry for replying late, I was out of station ...
