### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by Rdxsaaho** [BLUE-DEVIL1134/IronEye#30]
hii bro i got a error when i wa installing it in my ubuntu machine .

i was use it in my Android device and it was so cool but in my linux machine i got error

ERROR
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/rdx/Desktop/IronEye/IronEye/__main__.py", line 42, in <module>
    xffH)\xfb\x95?\xb2\x83\xdd\x7f\xc4\x13{\xc7I\xa0?w6\xef\xf2\x13\x87\xf2\xb1T\xfd\xc8\x0c]\x8f\xad\xf8d\xed\x00\xf5\xc6k=\xcf\xc6_Q\xfd{\x99\x97\xb9=\xc2\xb7w\x85\xb5\xcb\xa7*\x9e\xc0{\x9f\xf7$\xed\x19\x0f*\xd9\xfe\xc6~"y\xe7\x9b\x9a7\xcdj\xef\xcf\xf7\\\xd4Y\x9c\xf0\xab\xb4\x1e\xf3\xae)\xbb\x08\xf2\x18\xfd\x8f\xe8\xb9\xf3\x12\x1fH\x14o_\xa0\x9e\x07\xfcKIv\xccl2\xfeK\xde\xafG\xdd\x1cx*\x13\xe6\x198\xef\x8btT\x9f\xb6\xdfG\x07\xfc\xea\xd7\xeb<\xa0>}<\xe4\xe7=\xe0-\xba\x95\x8a_\xe1\xd63\x0e\xa7+\xecC\\\xf9\x1buy\x1b\x9e\xf4>\x90U\xbf\xe7I\'\xb90p\xdd\x05\xfc \x85\x13C>aN\x81\x93$;\x0e\xf2\x8cq\xce\x9c\xef\xa6\xfb\x84\xea\xcb\x8d\xfc\xe20g\xb0\x97\x12\xd4\xabgB\x8e\xfe\x1e\x8f\x93\xa0\xfe\xe8 \xce\xa0x#\xb6|\xcabW_\xc4\xbcO\xc0\xd3\x837\xa7\xb0P\xef\xe71\x9f\xf2\xcaK\xb2\xe1\x03a\x9e\x89c;.\xb6&\xe4\x1fv8\xa9d\xc7\xfb\x82}\xa2\xfa\x03\xd1<\xd2\xbeB=\xe5\xae\xdegSg\xc3}o\x9e\xed\xd5\x1d\xceon\x92\x1d>x\xca\xebR\xf5E&y\xd4\x8ed\xef\xa0l\x86\xec\xda\xf9\x86\xfeyi!\x06\xe0"\xc3\xc2#\xe3rj]\xc7D_\xccH\xe3\xf4\x12\xa3\x9d\xeb\x08x*\x12o\xa2G\x9e\xd1D\x1f!\x1a\xe7\x19nv\xed\xe3|\x86[_>\x13\xf0\x1a\xf8\xb6\xff\x05\xde\xe1\x8a\xfb\xfd\x0c\xad\x8f~\xd7\xa1\x11\xd4\x85hcp\x82\xd0\xf8\xe8\xfb\x17\xfd\x11\xdbQ\xf5}nQ\xf7\x14\x87\xa9\x13\x87\xb7\xd6\xc2\xb9\xe1uF\x9dw.\xdcu?w\xef\xf4[\xbc\xef\xefP8\xbe\xf6\x97\x97\xf5D\xfdyI\xf2"\x19\xb6\xeb\xdc;\xed\x94\x9b~r\x81\'_>+K\xf3;\x8f\xa6\xc2\x15\x83o\x84\xfc\xaa\xda\x0e\xca\xb2>\xad3I\x8c]\xfeW\x9f\x8b\x9a\xeb\xd8\x14\x7f\n\xeb\xd5\x9a\xec}\xf0\x07\x1e\xe08\x96\xbaE\xc5\x03\xc6~`n\xdf\x065~\xae\x0fRz\r}6{\xd4m\xa0\x8e}\x1b\xf7\xfc\x87\xed\xda\x15\xcfz\xa8\xff\xee\xd7\xd9f\xaa\xfc\xce@\xc5\xbf\xc8\xa1\xc59w\xc8\x0eRz\xe9@\x0f\xfd\xd5\xba-\x0f8\'\xb2\x7f\xb4?7\x06d\xaa\x8d\xa8?\x1b\x90\x7f\x97\xa8?\xd3\xf1\xbb\xaa\xa8}\xff\xa8>\x08\xf2\x8e\xfdCo\x91\x1fK\x9e`\xe7\xd7\xfe\xb3\xefy\x12?\xd9\xd95\xff\xc7\xff\xfd?\xca.9\x8d'
ValueError: bad marshal data (unknown type code)

**Comment by BLUE-DEVIL1134** [comment]
You need to upgrade to python 3.9.1,
For docs, see - cli.ironeye.cf

**Comment by BLUE-DEVIL1134** [comment]
@Rdxsaaho have you tried?

**Comment by BLUE-DEVIL1134** [comment]
Until @Rdxsaaho Replies, This Issue Is Solved I Guess As I Have Tried On Ubuntu and OpenSuse...
Worked Fine On Both...
